  𝙭 homeless-try: `try` cannot be used in functions that do not return errors.
   ╭─[homeless-try.zig:2:4]
 1 │ const std = @import("std");
 2 │ fn foo() void {
   ·    ─┬─
   ·     ╰── function `foo` is declared here.
 3 │   const x = try std.heap.page_allocator.alloc(u8, 8);
   ·             ─┬─
   ·              ╰── it cannot propegate error unions.
   ╰────
  help: Change the return type to `!void`.

  𝙭 homeless-try: `try` cannot be used outside of a function.
   ╭─[homeless-try.zig:2:11]
 1 │ const std = @import("std");
 2 │ const x = try std.heap.page_allocator.alloc(u8, 8);
   ·           ───
   ·           ─┬─
   ·            ╰── there is nowhere to propegate errors to.
   ╰────

  𝙭 homeless-try: `try` cannot be used outside of a function.
   ╭─[homeless-try.zig:4:17]
 3 │   const Bar = struct {
 4 │     baz: []u8 = try std.heap.page_allocator.alloc(u8, 8),
   ·                 ───
   ·                 ─┬─
   ·                  ╰── there is nowhere to propegate errors to.
 5 │   };
   ╰────

